### PR TITLE
Reorganize namespaces

### PR DESCRIPTION
**Pull request by Speykious**
Classes weren't really organized well before. Let me know what you think about this.

### CODE REVIEW

**Review by sr229 — APPROVED** [review]

**Comment by sr229** [comment]
Just wanna let you know this is a BREAKING change so you might want to inform about this

**Comment by Speykious** [comment]
Oh yeah I should change the version number in this PR as well

**Comment by adryzz** [comment]
just hold onto it and do a full release (3.0.0) including #13

**Comment by Speykious** [comment]
Yup, that's precisely my intention

**Comment by Speykious** [comment]
Let me know what you think of how I reorganized this

**Comment by sr229** [comment]
Looks like this is a cleaner API, definitely a good change.

**Comment by Speykious** [comment]
Yay :D

**Pull request merged**
