### PR TITLE
Camera config management

### PR DESCRIPTION
**Pull request by Speykious**
This PR adds a way to enumerate all video input options for a camera device.

As of now, it only supports DShow and V4l2 input formats, but maybe more will be supported in the future.

- [x] DShow
- [ ] VfWCap
- [ ] GdiGrab
- [x] V4l2
- [ ] X11Grab
- [ ] AVFoundation
- [ ] QTKit

I am not sure at all if other formats even need it... Until then, this is what we've got.

### CODE REVIEW

**Comment by Speykious** [comment]
I tested camera configuration with OBS virtual camera and it works. Tomorrow I'll test with my real webcam.

**Review by adryzz — COMMENTED** [review]
looks good, i'll test it now

**Comment by adryzz** [comment]
image

It apparently is trying to use `yuv420` while its name is `yuv420p`

**Review by adryzz — APPROVED** [review]
Works now on YUV. LGTM.

**Pull request merged**
