### PR TITLE
Enable more target frameworks

### PR DESCRIPTION
**Pull request by Speykious**
This PR aims at providing more target frameworks for SeeShark.

So far, `net6.0` and `net5.0` have been tested and validated. `netstandard2.1` has been tested but failed to build because of some `Immutable` stuff not existing in `System.Collections`, along with some other things I don't exactly remember.

Just having `net5.0` and `net6.0` is already fine imo, but the more we can have without changing anything in the code the better, so if you have any suggestions I'll gladly take them.

- [x] `net6.0`
- [x] `net5.0`
- [ ] `netstandard2.1` (nope)

### CODE REVIEW

**Review by sr229 — APPROVED** [review]
Take that net5.0 declaration out since that'll get deprecated soon. Also, netstandard is legacy since that culminated into .NET anyway.

**Comment by Speykious** [comment]
How soon is "soon"? Can we reasonably expect any project looking to integrate SeeShark in their tech stack to use `net6.0`?

**Comment by sr229** [comment]
> How soon is "soon"? Can we reasonably expect any project looking to integrate SeeShark in their tech stack to use `net6.0`?

IIRC most of the modern projects are using LTS now so I think it's wise to move to the LTS instead of supporting short term releases.

**Review by adryzz — COMMENTED** [review]
Yeah, as Ayane said net5.0  and netcoreapp3.1 are out of support before february 2022, so every app has to move to the next LTS release (net6.0).

**Comment by Speykious** [comment]
Looks like .NET 5 will be deprecated in about 6 months, and .NET Core 3.1 in about a year.
image
_interesting_

**Comment by Speykious** [comment]
Alright, then I'll refrain from adding any other target frameworks. It will also encourage others to migrate to LTS if using SeeShark is in their plan (if it ever happens that shortly anyway lol).

Closing this PR

**Pull request closed without merging**
